---

apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-monkey-config-map
  namespace: kube-system
data:
  config.toml: |
    [kubemonkey]
    run_hour = 20
    start_hour = 21
    end_hour = 23
    blacklisted_namespaces = ["kube-system"]
    whitelisted_namespaces = ["default"]
    time_zone = "Australia/Melbourne"
    graceperiod_sec= 10
    [debug]
    enabled= true
    schedule_immediate_kill= true
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kube-monkey
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-monkey
    spec:
      containers:
        -  name: kube-monkey
           command:
             - "/kube-monkey"
           args: ["-v=5", "-log_dir=/var/log/kube-monkey"]
           image: ayushsobti/kube-monkey:v0.2.3
           volumeMounts:
             - name: config-volume
               mountPath: "/etc/kube-monkey"
      volumes:
        - name: config-volume
          configMap:
            name: kube-monkey-config-map
      serviceAccountName: tiller
